spring.servlet.multipart.max-file-size= 20MB
spring.servlet.multipart.max-request-size= 20MB


spring.datasource.url=jdbc:sqlserver://localhost:1433;database=sale_website;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2;

spring.datasource.username=trieuluong01
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = none
spring.jpa.hibernate.database-platform=org.hibernate.dialect.SQLServer2012Dialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luongvantrieu.01@gmail.com
spring.mail.password=jtiqeeqgfrytjidz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port = 8080

#default INFO
logging.level.org.springframework.security = INFO

#default INFO
logging.level.org.springframework.jdbc = INFO

#default false
spring.h2.console.enabled=true

#default value /h2-console
spring.h2.console.path=/h2-console

#default spring ceates a random name
spring.datasource.generate-unique-name=false
